### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by bravoga** [Wicker25/whatstrapp#3]
When you start it only appears "connected" in the browser. What can be?

**Comment by bravoga** [comment]
[::ffff:172.18.0.1] ~> starting new session
whatstrapp_1     | (node:130) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Target closed.
whatstrapp_1     |     at Promise (/app/node_modules/puppeteer/lib/Connection.js:202:56)
whatstrapp_1     |     at new Promise (<anonymous>)
whatstrapp_1     |     at CDPSession.send (/app/node_modules/puppeteer/lib/Connection.js:201:12)
whatstrapp_1     |     at navigate (/app/node_modules/puppeteer/lib/Page.js:601:39)
whatstrapp_1     |     at Page.goto (/app/node_modules/puppeteer/lib/Page.js:581:7)
whatstrapp_1     |     at Browser._openPage (/app/lib/browser.js:95:27)
whatstrapp_1     |     at <anonymous>
whatstrapp_1     |     at process._tickCallback (internal/process/next_tick.js:189:7)
whatstrapp_1     | (node:130) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
whatstrapp_1     | (node:130) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
