### ISSUE TITLE
Connects but does not appear QR CODE

### ISSUE THREAD

**Issue by GioCarl** [Wicker25/whatstrapp#4]
Hi friends, I tested with Debian 10, ubuntu 18.04 and Windows. Both give the same error, what can it be? Below is the error you are giving. I just need to save the conversation history.

whatstrapp_1_44ef4deff719 | (node:131) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
whatstrapp_1_44ef4deff719 |     at Promise.then (/app/node_modules/puppeteer/lib/NavigatorWatcher.js:74:21)
whatstrapp_1_44ef4deff719 |     at <anonymous>
whatstrapp_1_44ef4deff719 | (node:131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
whatstrapp_1_44ef4deff719 | (node:131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Wicker25** [comment]
Hi @GioCarl ,

I just updated the User-Agent used by Puppeteer to access Whatsapp Web's APIs and now the issue seems to be solved. Could you double test my changes pulling the master branch?

Thank you,
Giacomo

**Comment by GioCarl** [comment]
Hello Wicker25, thanks for replying. 

Unfortunately it didn't work, am I doing something wrong? I suspect the elasticsearch version. I tested with the latest version of Debian and Ubuntu. It keeps giving connected but does not generate QRCODE.

Below I put what generates when I open the page on port 8025:

 [::ffff:172.16.10.44] ~> connected
 [::ffff:172.16.10.44] ~> starting new session
  (node:124) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
     at Function.keys (<anonymous>)
     at new Response (/app/node_modules/puppeteer/lib/NetworkManager.js:556:30)
     at Page.<anonymous> (/app/lib/proxy.js:50:26)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:189:7)
 (node:124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 (node:124) UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
     at Promise.then (/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21)
     at <anonymous>
   -- ASYNC --
     at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:111:15)
     at Page.goto (/app/node_modules/puppeteer/lib/Page.js:674:49)
     at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:112:23)
     at Browser._openPage (/app/lib/browser.js:98:27)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:189:7)
(node:124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2).

**Comment by Wicker25** [comment]
Hi, @GioCarl ,

Please, could you try to pull the master branch again and get the new Docker's images?

```
$ git pull origin master
$ docker-compose up
```

If the issue persists, you can try to apply this [patch.txt](https://github.com/Wicker25/whatstrapp/files/3483619/patch.txt). You need only to run `git apply patch.txt`.

After you did so, run `docker-compose up` and `yarn start` in two different terminals: you will be able to access the Chrome's console and see what's going on. 

Thank you!

**Comment by GioCarl** [comment]
Hi Wicker25, 

patch.txt did not work, gave errors. I manually made steps of it and it didn't work either, installed the webpack that was not installed and some others. I recompiled git and it worked QRCODE too. Kibana does not seem to be capturing where it should, via terminal after connecting with mobile ...

whatstrapp_1_9b0d6f1b80be | [:: ffff: 172.16.10.44] ~> connected
whatstrapp_1_9b0d6f1b80be | [:: ffff: 172.16.10.44] ~> starting new session
whatstrapp_1_9b0d6f1b80be | [:: ffff: 127.0.0.1] ~> connected
whatstrapp_1_9b0d6f1b80be | [:: ffff: 127.0.0.1] ~> puppet ~ weorhpao0n: the QR Code has been sent to the client
whatstrapp_1_9b0d6f1b80be | [:: ffff: 127.0.0.1] ~> puppet ~ weorhpao0n: the QR Code has been sent to the client

When I browse Kibana, it shows logging in the terminal, but not what is communicated on whatsapp via mobile. I changed his update time and did some other testing via web interface, without success. What can it be?
